server {
    listen 80;
    server_name rabs.my.id;
    return 301 https://$host$request_uri;
}


server {

    listen              443 ssl;
    server_name         rabs.my.id;
    keepalive_timeout   70;

    ssl_certificate     /etc/nginx/ssl/certificate.pem;
    ssl_certificate_key /etc/nginx/ssl/private.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 10M;
    
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 104.16.0.0/13;
    set_real_ip_from 104.24.0.0/14;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 131.0.72.0/22;
    
    real_ip_header CF-Connecting-IP;
    # KUNCI PERBAIKAN: Support React Router
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Jika url selain yang ditentukan dipanggil, Nginx akan tetap memberikan index.html
        try_files $uri $uri/ /index.html;
    }

    # Static Files Django (Admin CSS, dll)
    location /static/ {
        alias /app/staticfiles/;
    }

    location /api/static/ {
        alias /app/staticfiles/;
    }


    # Media Files Django
    location /media/ {
        alias /var/www/media/;
    }

    # Proxy ke Backend Django API
    location /api/ {
	location /api/admin/ {
        	deny all;
    	}

        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
    }

    # Proxy ke Django Admin
    location /admin/ {
	allow 182.10.161.231;
	allow 2404:c0:ab01:ef96:bc91:b655:ef78:f607;
	deny all;

        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
    }

    # Proxy websocket
    location /api/ws/ {
    proxy_pass http://backend:8000;  # Arahkan ke service backend rabs
    
    # Konfigurasi wajib WebSocket
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Header tambahan (sama seperti API biasa)
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;

    # Pengaturan Timeout (Penting untuk IoT)
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
}
}
