# Generated by Django 6.0.2 on 2026-03-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDevice', models.CharField(editable=False, max_length=10, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Device')),
                ('type', models.CharField(choices=[('sensor', 'Sensor'), ('aktuator', 'Aktuator')], max_length=10, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxValue', models.IntegerField(verbose_name='Nilai maksimal')),
                ('threshold', models.IntegerField(verbose_name='Nilai ambang batas')),
                ('status', models.BooleanField(choices=[('on', True), ('off', False)], verbose_name='Status Aktuator')),
                ('measurement', models.CharField(max_length=10, verbose_name='Satuan Ukur')),
                ('value', models.IntegerField(verbose_name='Nilai Sensor')),
                ('device', models.OneToOneField(limit_choices_to={'type': 'sensor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='device.device', to_field='name', verbose_name='Device')),
            ],
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[('on', True), ('off', False)], verbose_name='Status Aktuator')),
                ('activation', models.CharField(choices=[('sensor', 'Berdasarkan Sensor'), ('manual', 'Manual')], max_length=6, verbose_name='Aktifasi Aktuator')),
                ('activationValue', models.IntegerField(blank=True, null=True, verbose_name='Nilai Aktifasi Aktuator')),
                ('compararison', models.CharField(blank=True, choices=[('==', '=='), ('<=', '<='), ('>=', '>=')], max_length=10, null=True, verbose_name='Perbandingan')),
                ('value', models.IntegerField(verbose_name='Nilai Sensor')),
                ('device', models.OneToOneField(limit_choices_to={'type': 'aktuator'}, on_delete=django.db.models.deletion.CASCADE, related_name='actuator', to='device.device', to_field='name', verbose_name='Device')),
                ('sensorTarget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.sensor', verbose_name='Sensor Target')),
            ],
        ),
    ]
