# Generated by Django 6.0.2 on 2026-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='status',
            field=models.BooleanField(choices=[(True, 'On'), (False, 'Off')], verbose_name='Status Aktuator'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Nilai Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(choices=[(True, 'On'), (False, 'Off')], verbose_name='Status Aktuator'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Nilai Sensor'),
        ),
    ]
