# Generated by Django 6.0.2 on 2026-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_actuator_status_alter_actuator_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='value',
        ),
        migrations.AlterField(
            model_name='actuator',
            name='compararison',
            field=models.CharField(blank=True, choices=[('==', '=='), ('<=', '<='), ('>=', '>=')], max_length=5, null=True, verbose_name='Perbandingan'),
        ),
    ]
