# Generated by Django 6.0.2 on 2026-03-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_actuator_value_alter_actuator_compararison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='device',
            field=models.OneToOneField(limit_choices_to={'type': 'actuator'}, on_delete=django.db.models.deletion.CASCADE, related_name='actuator', to='device.device', to_field='name', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(choices=[(True, 'On'), (False, 'Off')], verbose_name='Status Sensor'),
        ),
    ]
