# Generated by Django 6.0.2 on 2026-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_actuator_device_alter_sensor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator')], max_length=10, verbose_name='Type'),
        ),
    ]
