# Generated by Django 6.0.2 on 2026-03-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='chart',
            field=models.CharField(choices=[('line', 'Line Chart'), ('doughnut', 'Doughnut Chart'), ('bar', 'Bar Chart')], default='bar', max_length=10, verbose_name='Chart Type'),
        ),
    ]
