# Generated by Django 6.0.2 on 2026-03-11 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_sensor_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='value',
        ),
        migrations.CreateModel(
            name='ValueSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Value Sensor')),
                ('device', models.ForeignKey(limit_choices_to={'type': 'sensor'}, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='device.device', to_field='name', verbose_name='Device')),
            ],
        ),
    ]
