# Generated by Django 6.0.2 on 2026-03-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alter_actuator_sensortarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='sensorTarget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.sensor', verbose_name='Sensor Target'),
        ),
    ]
