# Generated by Django 6.0.2 on 2026-03-14 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_actuator_sensortarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='compararison',
            new_name='comparison',
        ),
        migrations.AddField(
            model_name='valuesensor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actuator',
            name='device',
            field=models.OneToOneField(limit_choices_to={'type': 'actuator'}, on_delete=django.db.models.deletion.CASCADE, related_name='actuator', to='device.device', to_field='idDevice', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.OneToOneField(limit_choices_to={'type': 'sensor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='device.device', to_field='idDevice', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='valuesensor',
            name='device',
            field=models.ForeignKey(limit_choices_to={'type': 'sensor'}, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='device.device', to_field='idDevice', verbose_name='Device'),
        ),
    ]
