# Generated by Django 6.0.2 on 2026-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_rename_compararison_actuator_comparison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='last_activation',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Terakhir Aktif'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measurement',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Satuan Ukur'),
        ),
    ]
