# Generated by Django 6.0.2 on 2026-03-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_actuator_last_activation_alter_sensor_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='sensorTarget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.sensor', verbose_name='Sensor Target'),
        ),
    ]
